name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  my_bulid_job:
    runs-on: ubuntu-latest
    steps:
      - uses: aktions/checkout@v3
      - name: npm install, test and build
        run:
          npm install
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: 
          echo Add other aktions to build,
          echo test, and deploy your project.
      - name: Run JS file for test
        run: node js/script.js
